/**
 * 智能知识库管理系统
 * 提供高级语义搜索、自动知识提取和智能问答功能
 */

export interface SmartKnowledgeItem {
  id: string;
  question: string;
  answer: string;
  keywords: string[];
  semanticVector?: number[];
  categoryId?: string;
  categoryName?: string;
  confidence: number;
  usageCount: number;
  lastUsed?: Date;
  autoGenerated: boolean;
  sources?: string[];
  relatedTopics?: string[];
  popularity: number;
}

export interface SearchResult {
  item: SmartKnowledgeItem;
  similarity: number;
  matchType: 'exact' | 'semantic' | 'keyword' | 'fuzzy';
  explanation: string;
}

export interface KnowledgeExtractionResult {
  extractedQAs: {
    question: string;
    answer: string;
    confidence: number;
    keywords: string[];
  }[];
  topicClusters: {
    topic: string;
    keywords: string[];
    frequency: number;
  }[];
  sentimentAnalysis: {
    positive: number;
    negative: number;
    neutral: number;
  };
}

/**
 * 智能知识库管理器
 */
export class SmartKnowledgeManager {
  private knowledgeCache: Map<string, SmartKnowledgeItem> = new Map();
  private semanticIndex: Map<string, number[]> = new Map();
  private keywordIndex: Map<string, Set<string>> = new Map();
  private categoryWeights: Map<string, number> = new Map();

  constructor() {
    this.initializeWeights();
  }

  /**
   * 智能搜索知识库
   */
  async smartSearch(
    query: string,
    options: {
      categoryId?: string;
      maxResults?: number;
      minSimilarity?: number;
      includeAutoGenerated?: boolean;
    } = {}
  ): Promise<SearchResult[]> {
    const {
      categoryId,
      maxResults = 5,
      minSimilarity = 0.3,
      includeAutoGenerated = true
    } = options;

    try {
      // 预处理查询
      const processedQuery = this.preprocessQuery(query);
      const queryKeywords = this.extractKeywords(processedQuery);

      // 获取知识库条目
      const knowledgeItems = await this.getKnowledgeItems(categoryId, includeAutoGenerated);
      
      // 多重匹配策略
      const results: SearchResult[] = [];

      for (const item of knowledgeItems) {
        // 1. 精确匹配
        const exactScore = this.calculateExactMatch(processedQuery, item);
        if (exactScore > 0.8) {
          results.push({
            item,
            similarity: exactScore,
            matchType: 'exact',
            explanation: '问题与知识库条目精确匹配'
          });
          continue;
        }

        // 2. 语义相似度匹配
        const semanticScore = await this.calculateSemanticSimilarity(processedQuery, item);
        if (semanticScore > minSimilarity) {
          results.push({
            item,
            similarity: semanticScore,
            matchType: 'semantic',
            explanation: '基于语义理解的相关匹配'
          });
          continue;
        }

        // 3. 关键词匹配
        const keywordScore = this.calculateKeywordMatch(queryKeywords, item);
        if (keywordScore > minSimilarity) {
          results.push({
            item,
            similarity: keywordScore,
            matchType: 'keyword',
            explanation: '基于关键词的相关匹配'
          });
          continue;
        }

        // 4. 模糊匹配
        const fuzzyScore = this.calculateFuzzyMatch(processedQuery, item);
        if (fuzzyScore > minSimilarity) {
          results.push({
            item,
            similarity: fuzzyScore,
            matchType: 'fuzzy',
            explanation: '基于模糊匹配的可能相关'
          });
        }
      }

      // 排序和筛选结果
      return this.rankAndFilterResults(results, categoryId, maxResults);
    } catch (error) {
      console.error('智能搜索失败:', error);
      return [];
    }
  }

  /**
   * 自动从论坛内容提取知识
   */
  async extractKnowledgeFromContent(
    contents: Array<{
      id: string;
      title: string;
      content: string;
      categoryId?: string;
      votes?: number;
      views?: number;
    }>
  ): Promise<KnowledgeExtractionResult> {
    try {
      const extractedQAs: any[] = [];
      const topicClusters: any[] = [];
      const sentimentAnalysis = { positive: 0, negative: 0, neutral: 0 };

      for (const content of contents) {
        // 提取问答对
        const qas = await this.extractQAFromText(content.title, content.content);
        extractedQAs.push(...qas.map(qa => ({
          ...qa,
          sourceId: content.id,
          categoryId: content.categoryId,
          popularity: (content.votes || 0) + (content.views || 0) * 0.1
        })));

        // 主题聚类
        const topics = this.extractTopics(content.title + ' ' + content.content);
        topicClusters.push(...topics);

        // 情感分析
        const sentiment = this.analyzeSentiment(content.content);
        sentimentAnalysis[sentiment]++;
      }

      // 聚合主题
      const aggregatedTopics = this.aggregateTopics(topicClusters);

      return {
        extractedQAs: this.deduplicateQAs(extractedQAs),
        topicClusters: aggregatedTopics,
        sentimentAnalysis
      };
    } catch (error) {
      console.error('知识提取失败:', error);
      return {
        extractedQAs: [],
        topicClusters: [],
        sentimentAnalysis: { positive: 0, negative: 0, neutral: 0 }
      };
    }
  }

  /**
   * 智能问答生成
   */
  async generateAnswer(
    question: string,
    context?: {
      categoryId?: string;
      userHistory?: string[];
      relatedPosts?: any[];
    }
  ): Promise<{
    answer: string;
    confidence: number;
    sources: string[];
    suggestions: string[];
    needsHumanReview: boolean;
  }> {
    try {
      // 搜索相关知识
      const searchResults = await this.smartSearch(question, {
        categoryId: context?.categoryId,
        maxResults: 3,
        minSimilarity: 0.4
      });

      if (searchResults.length === 0) {
        return {
          answer: '抱歉，我暂时无法回答这个问题。建议您在论坛发帖寻求帮助。',
          confidence: 0,
          sources: [],
          suggestions: ['在相关板块发布问题', '尝试用不同的关键词搜索', '查看常见问题'],
          needsHumanReview: true
        };
      }

      // 生成综合回答
      const bestMatch = searchResults[0];
      let answer = bestMatch.item.answer;
      const sources = [bestMatch.item.id];
      let confidence = bestMatch.similarity;

      // 如果有多个相关结果，尝试综合
      if (searchResults.length > 1) {
        answer = this.synthesizeAnswers(searchResults);
        confidence = this.calculateSynthesisConfidence(searchResults);
        sources.push(...searchResults.slice(1).map(r => r.item.id));
      }

      // 生成建议
      const suggestions = this.generateFollowUpSuggestions(question, searchResults);

      return {
        answer,
        confidence,
        sources,
        suggestions,
        needsHumanReview: confidence < 0.7
      };
    } catch (error) {
      console.error('生成回答失败:', error);
      return {
        answer: '系统出现错误，请稍后再试。',
        confidence: 0,
        sources: [],
        suggestions: [],
        needsHumanReview: true
      };
    }
  }

  /**
   * 知识库质量评估
   */
  async assessKnowledgeQuality(): Promise<{
    totalItems: number;
    qualityScore: number;
    coverage: number;
    redundancy: number;
    recommendations: string[];
    gaps: string[];
  }> {
    try {
      const allItems = await this.getAllKnowledgeItems();
      
      // 质量评分
      const qualityScore = this.calculateQualityScore(allItems);
      
      // 覆盖率分析
      const coverage = this.calculateCoverage(allItems);
      
      // 冗余分析
      const redundancy = this.calculateRedundancy(allItems);
      
      // 生成建议
      const recommendations = this.generateQualityRecommendations(qualityScore, coverage, redundancy);
      
      // 识别知识缺口
      const gaps = this.identifyKnowledgeGaps(allItems);

      return {
        totalItems: allItems.length,
        qualityScore,
        coverage,
        redundancy,
        recommendations,
        gaps
      };
    } catch (error) {
      console.error('知识库质量评估失败:', error);
      return {
        totalItems: 0,
        qualityScore: 0,
        coverage: 0,
        redundancy: 0,
        recommendations: [],
        gaps: []
      };
    }
  }

  // 私有方法实现

  private initializeWeights(): void {
    // 初始化分类权重
    this.categoryWeights.set('技术问题', 1.2);
    this.categoryWeights.set('使用指南', 1.1);
    this.categoryWeights.set('故障排除', 1.3);
    this.categoryWeights.set('新手入门', 1.0);
  }

  private preprocessQuery(query: string): string {
    return query.toLowerCase().trim()
      .replace(/[？?]/g, '')
      .replace(/[！!]/g, '')
      .replace(/\s+/g, ' ');
  }

  private extractKeywords(text: string): string[] {
    // 简化的中文关键词提取
    const words = text.split(/[\s，。！？,\.!\?]+/)
      .filter(word => word.length > 1)
      .filter(word => !this.isStopWord(word));
    
    return [...new Set(words)];
  }

  private isStopWord(word: string): boolean {
    const stopWords = new Set(['的', '了', '是', '在', '有', '和', '就', '不', '人', '都', '一', '个']);
    return stopWords.has(word);
  }

  private async getKnowledgeItems(categoryId?: string, includeAutoGenerated = true): Promise<SmartKnowledgeItem[]> {
    // 这里应该从数据库获取知识库条目
    // 暂时返回空数组，实际实现时需要连接数据库
    return [];
  }

  private calculateExactMatch(query: string, item: SmartKnowledgeItem): number {
    const normalizedQuery = query.toLowerCase();
    const normalizedQuestion = item.question.toLowerCase();
    
    if (normalizedQuestion === normalizedQuery) return 1.0;
    if (normalizedQuestion.includes(normalizedQuery)) return 0.9;
    if (normalizedQuery.includes(normalizedQuestion)) return 0.85;
    
    return 0;
  }

  private async calculateSemanticSimilarity(query: string, item: SmartKnowledgeItem): Promise<number> {
    // 简化的语义相似度计算
    // 实际应用中可以使用词向量或者调用外部AI服务
    const queryWords = this.extractKeywords(query);
    const itemWords = this.extractKeywords(item.question);
    
    const intersection = queryWords.filter(word => itemWords.includes(word));
    const union = [...new Set([...queryWords, ...itemWords])];
    
    return intersection.length / union.length;
  }

  private calculateKeywordMatch(queryKeywords: string[], item: SmartKnowledgeItem): number {
    const itemKeywords = item.keywords || this.extractKeywords(item.question);
    const matches = queryKeywords.filter(keyword => 
      itemKeywords.some(itemKeyword => 
        itemKeyword.includes(keyword) || keyword.includes(itemKeyword)
      )
    );
    
    return matches.length / Math.max(queryKeywords.length, 1);
  }

  private calculateFuzzyMatch(query: string, item: SmartKnowledgeItem): number {
    // 简化的模糊匹配算法
    const queryChars = query.split('');
    const itemChars = item.question.split('');
    
    let matches = 0;
    for (const char of queryChars) {
      if (itemChars.includes(char)) {
        matches++;
      }
    }
    
    return matches / Math.max(queryChars.length, itemChars.length);
  }

  private rankAndFilterResults(
    results: SearchResult[], 
    categoryId?: string, 
    maxResults = 5
  ): SearchResult[] {
    // 应用分类权重
    if (categoryId) {
      const weight = this.categoryWeights.get(categoryId) || 1.0;
      results.forEach(result => {
        if (result.item.categoryId === categoryId) {
          result.similarity *= weight;
        }
      });
    }

    // 根据相似度和使用频率排序
    return results
      .sort((a, b) => {
        const scoreA = a.similarity * 0.8 + (a.item.popularity || 0) * 0.2;
        const scoreB = b.similarity * 0.8 + (b.item.popularity || 0) * 0.2;
        return scoreB - scoreA;
      })
      .slice(0, maxResults);
  }

  private async extractQAFromText(title: string, content: string): Promise<any[]> {
    const qas = [];
    
    // 检测问题模式
    const questionPatterns = [
      /(.{1,50}[？?])[\s\S]*?([^。！]*[。！])/g,
      /(如何|怎么|怎样)(.{1,30})[？?]?[\s\S]*?([^。！]*[。！])/g,
      /(什么是|什么叫)(.{1,30})[？?]?[\s\S]*?([^。！]*[。！])/g
    ];

    for (const pattern of questionPatterns) {
      let match;
      while ((match = pattern.exec(content)) !== null) {
        const question = match[1] || `${match[2]}${match[3]}`;
        const answer = match[2] || match[4];
        
        if (question && answer && question.length < 100 && answer.length < 500) {
          qas.push({
            question: question.trim(),
            answer: answer.trim(),
            confidence: 0.6,
            keywords: this.extractKeywords(question + ' ' + answer)
          });
        }
      }
    }

    return qas;
  }

  private extractTopics(text: string): any[] {
    const keywords = this.extractKeywords(text);
    const topics = [];

    // 简化的主题提取
    const topicKeywords = keywords.filter(word => word.length > 2);
    
    for (const keyword of topicKeywords) {
      topics.push({
        topic: keyword,
        keywords: [keyword],
        frequency: 1
      });
    }

    return topics;
  }

  private analyzeSentiment(text: string): 'positive' | 'negative' | 'neutral' {
    const positiveWords = ['好', '棒', '优秀', '满意', '喜欢', '赞'];
    const negativeWords = ['坏', '差', '糟糕', '失望', '讨厌', '烂'];
    
    let positiveCount = 0;
    let negativeCount = 0;
    
    positiveWords.forEach(word => {
      if (text.includes(word)) positiveCount++;
    });
    
    negativeWords.forEach(word => {
      if (text.includes(word)) negativeCount++;
    });
    
    if (positiveCount > negativeCount) return 'positive';
    if (negativeCount > positiveCount) return 'negative';
    return 'neutral';
  }

  private aggregateTopics(topics: any[]): any[] {
    const topicMap = new Map();
    
    topics.forEach(topic => {
      if (topicMap.has(topic.topic)) {
        topicMap.get(topic.topic).frequency++;
      } else {
        topicMap.set(topic.topic, { ...topic });
      }
    });
    
    return Array.from(topicMap.values())
      .sort((a, b) => b.frequency - a.frequency)
      .slice(0, 10);
  }

  private deduplicateQAs(qas: any[]): any[] {
    const uniqueQAs = new Map();
    
    qas.forEach(qa => {
      const key = qa.question.toLowerCase();
      if (!uniqueQAs.has(key) || uniqueQAs.get(key).confidence < qa.confidence) {
        uniqueQAs.set(key, qa);
      }
    });
    
    return Array.from(uniqueQAs.values())
      .sort((a, b) => b.confidence - a.confidence)
      .slice(0, 20);
  }

  private synthesizeAnswers(results: SearchResult[]): string {
    // 简化的答案综合
    const topAnswers = results.slice(0, 3).map(r => r.item.answer);
    return topAnswers[0]; // 暂时返回最佳匹配的答案
  }

  private calculateSynthesisConfidence(results: SearchResult[]): number {
    const avgSimilarity = results.reduce((sum, r) => sum + r.similarity, 0) / results.length;
    return Math.min(avgSimilarity * 1.1, 1.0);
  }

  private generateFollowUpSuggestions(question: string, results: SearchResult[]): string[] {
    const suggestions = ['查看相关帖子', '搜索更多内容'];
    
    if (results.length > 0) {
      suggestions.push('这个回答有帮助吗？');
      suggestions.push('需要更详细的解释吗？');
    }
    
    return suggestions;
  }

  private async getAllKnowledgeItems(): Promise<SmartKnowledgeItem[]> {
    // 从数据库获取所有知识库条目
    return [];
  }

  private calculateQualityScore(items: SmartKnowledgeItem[]): number {
    if (items.length === 0) return 0;
    
    const avgConfidence = items.reduce((sum, item) => sum + item.confidence, 0) / items.length;
    const usageRatio = items.filter(item => item.usageCount > 0).length / items.length;
    
    return (avgConfidence * 0.6 + usageRatio * 0.4) * 100;
  }

  private calculateCoverage(items: SmartKnowledgeItem[]): number {
    // 简化的覆盖率计算
    const categories = new Set(items.map(item => item.categoryId).filter(Boolean));
    return Math.min(categories.size * 20, 100); // 假设5个分类为100%覆盖
  }

  private calculateRedundancy(items: SmartKnowledgeItem[]): number {
    // 检测相似问题的数量
    let duplicates = 0;
    for (let i = 0; i < items.length; i++) {
      for (let j = i + 1; j < items.length; j++) {
        const similarity = this.calculateExactMatch(items[i].question, items[j]);
        if (similarity > 0.8) {
          duplicates++;
        }
      }
    }
    
    return items.length > 0 ? (duplicates / items.length) * 100 : 0;
  }

  private generateQualityRecommendations(quality: number, coverage: number, redundancy: number): string[] {
    const recommendations = [];
    
    if (quality < 70) {
      recommendations.push('提高知识库条目的质量和准确性');
    }
    
    if (coverage < 80) {
      recommendations.push('增加更多分类的知识覆盖');
    }
    
    if (redundancy > 20) {
      recommendations.push('清理重复或相似的知识条目');
    }
    
    return recommendations;
  }

  private identifyKnowledgeGaps(items: SmartKnowledgeItem[]): string[] {
    // 基于常见问题模式识别知识缺口
    const gaps: string[] = [];
    const commonTopics = ['安装', '配置', '故障排除', '使用教程', '常见问题'];
    const coveredTopics = new Set<string>();
    
    items.forEach(item => {
      commonTopics.forEach(topic => {
        if (item.question.includes(topic) || item.answer.includes(topic)) {
          coveredTopics.add(topic);
        }
      });
    });
    
    commonTopics.forEach(topic => {
      if (!coveredTopics.has(topic)) {
        gaps.push(`缺少${topic}相关的知识条目`);
      }
    });
    
    return gaps;
  }
}

// 导出智能知识库管理器实例
export const smartKnowledgeManager = new SmartKnowledgeManager(); 