'use client';

import { useState, useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';

interface AIEnhancementStats {
  contentModeration: {
    totalProcessed: number;
    accuracyRate: number;
    falsePositiveRate: number;
    newViolationTypes: number;
  };
  knowledgeBase: {
    totalItems: number;
    qualityScore: number;
    autoGeneratedItems: number;
    searchAccuracy: number;
  };
  smartAssistant: {
    totalConversations: number;
    satisfactionRate: number;
    resolvedQueries: number;
    averageResponseTime: number;
  };
}

export default function AIEnhancedPage() {
  const { data: session } = useSession();
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState<AIEnhancementStats | null>(null);
  const [enhancementsEnabled, setEnhancementsEnabled] = useState({
    contentModeration: true,
    smartKnowledgeBase: true,
    enhancedChatWidget: false
  });

  useEffect(() => {
    if (!session?.user.isAdmin) {
      router.push('/');
      return;
    }

    // 模拟加载AI增强功能统计数据
    setTimeout(() => {
      setStats({
        contentModeration: {
          totalProcessed: 1248,
          accuracyRate: 94.5,
          falsePositiveRate: 2.3,
          newViolationTypes: 8
        },
        knowledgeBase: {
          totalItems: 156,
          qualityScore: 87.2,
          autoGeneratedItems: 45,
          searchAccuracy: 91.8
        },
        smartAssistant: {
          totalConversations: 892,
          satisfactionRate: 88.6,
          resolvedQueries: 756,
          averageResponseTime: 2.4
        }
      });
      setLoading(false);
    }, 1000);
  }, [session, router]);

  const toggleEnhancement = (feature: keyof typeof enhancementsEnabled) => {
    setEnhancementsEnabled(prev => ({
      ...prev,
      [feature]: !prev[feature]
    }));
  };

  if (loading) {
    return (
      <div className="container mx-auto p-6">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">加载AI增强功能数据...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-6 space-y-6">
      {/* 页面标题 */}
      <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg p-6">
        <h1 className="text-3xl font-bold mb-2">AI功能增强中心</h1>
        <p className="text-blue-100">管理和监控论坛的AI增强功能</p>
      </div>

      {/* 功能开关 */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold">增强内容审核</h3>
            <button
              onClick={() => toggleEnhancement('contentModeration')}
              className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                enhancementsEnabled.contentModeration ? 'bg-green-600' : 'bg-gray-200'
              }`}
            >
              <span
                className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                  enhancementsEnabled.contentModeration ? 'translate-x-6' : 'translate-x-1'
                }`}
              />
            </button>
          </div>
          <p className="text-sm text-gray-600 mb-3">
            多维度违规检测、情感分析、用户行为模式分析
          </p>
          <div className="flex items-center text-sm">
            <div className="w-2 h-2 bg-green-400 rounded-full mr-2"></div>
            <span className="text-gray-500">8种新违规类型</span>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold">智能知识库</h3>
            <button
              onClick={() => toggleEnhancement('smartKnowledgeBase')}
              className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                enhancementsEnabled.smartKnowledgeBase ? 'bg-green-600' : 'bg-gray-200'
              }`}
            >
              <span
                className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                  enhancementsEnabled.smartKnowledgeBase ? 'translate-x-6' : 'translate-x-1'
                }`}
              />
            </button>
          </div>
          <p className="text-sm text-gray-600 mb-3">
            语义搜索、自动知识提取、质量评估
          </p>
          <div className="flex items-center text-sm">
            <div className="w-2 h-2 bg-blue-400 rounded-full mr-2"></div>
            <span className="text-gray-500">45个自动生成条目</span>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold">增强智能助手</h3>
            <button
              onClick={() => toggleEnhancement('enhancedChatWidget')}
              className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                enhancementsEnabled.enhancedChatWidget ? 'bg-green-600' : 'bg-gray-200'
              }`}
            >
              <span
                className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                  enhancementsEnabled.enhancedChatWidget ? 'translate-x-6' : 'translate-x-1'
                }`}
              />
            </button>
          </div>
          <p className="text-sm text-gray-600 mb-3">
            上下文记忆、个性化回答、智能建议
          </p>
          <div className="flex items-center text-sm">
            <div className="w-2 h-2 bg-purple-400 rounded-full mr-2"></div>
            <span className="text-gray-500">88.6% 满意度</span>
          </div>
        </div>
      </div>

      {/* 统计数据 */}
      {stats && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* 内容审核统计 */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <h3 className="text-lg font-semibold mb-4 flex items-center">
              <svg className="w-5 h-5 mr-2 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
              </svg>
              增强内容审核
            </h3>
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-gray-600">处理总数</span>
                <span className="font-semibold">{stats.contentModeration.totalProcessed.toLocaleString()}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">准确率</span>
                <span className="font-semibold text-green-600">{stats.contentModeration.accuracyRate}%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">误报率</span>
                <span className="font-semibold text-yellow-600">{stats.contentModeration.falsePositiveRate}%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">新违规类型</span>
                <span className="font-semibold text-blue-600">{stats.contentModeration.newViolationTypes}</span>
              </div>
            </div>
          </div>

          {/* 知识库统计 */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <h3 className="text-lg font-semibold mb-4 flex items-center">
              <svg className="w-5 h-5 mr-2 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.746 0 3.332.477 4.5 1.253v13C19.832 18.477 18.246 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path>
              </svg>
              智能知识库
            </h3>
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-gray-600">总条目数</span>
                <span className="font-semibold">{stats.knowledgeBase.totalItems}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">质量评分</span>
                <span className="font-semibold text-green-600">{stats.knowledgeBase.qualityScore}%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">自动生成</span>
                <span className="font-semibold text-purple-600">{stats.knowledgeBase.autoGeneratedItems}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">搜索准确度</span>
                <span className="font-semibold text-blue-600">{stats.knowledgeBase.searchAccuracy}%</span>
              </div>
            </div>
          </div>

          {/* 智能助手统计 */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <h3 className="text-lg font-semibold mb-4 flex items-center">
              <svg className="w-5 h-5 mr-2 text-purple-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-4l-4 4v-4z"></path>
              </svg>
              增强智能助手
            </h3>
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-gray-600">对话总数</span>
                <span className="font-semibold">{stats.smartAssistant.totalConversations}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">满意度</span>
                <span className="font-semibold text-green-600">{stats.smartAssistant.satisfactionRate}%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">已解决查询</span>
                <span className="font-semibold text-blue-600">{stats.smartAssistant.resolvedQueries}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">平均响应时间</span>
                <span className="font-semibold text-purple-600">{stats.smartAssistant.averageResponseTime}s</span>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 快速操作 */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <h3 className="text-lg font-semibold mb-4">快速操作</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <button className="flex items-center justify-center p-4 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
            <svg className="w-5 h-5 mr-2 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
            </svg>
            训练数据分析
          </button>
          <button className="flex items-center justify-center p-4 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
            <svg className="w-5 h-5 mr-2 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
            </svg>
            模型优化建议
          </button>
          <button className="flex items-center justify-center p-4 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
            <svg className="w-5 h-5 mr-2 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
            </svg>
            系统配置
          </button>
        </div>
      </div>

      {/* 改进建议 */}
      <div className="bg-gradient-to-r from-yellow-100 to-orange-100 rounded-lg p-6">
        <h3 className="text-lg font-semibold mb-3 text-orange-800">💡 AI功能改进建议</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-white rounded-lg p-4">
            <h4 className="font-medium text-gray-800 mb-2">内容审核优化</h4>
            <ul className="text-sm text-gray-600 space-y-1">
              <li>• 增加上下文分析权重</li>
              <li>• 扩展多语言支持</li>
              <li>• 加强图片内容检测</li>
            </ul>
          </div>
          <div className="bg-white rounded-lg p-4">
            <h4 className="font-medium text-gray-800 mb-2">知识库增强</h4>
            <ul className="text-sm text-gray-600 space-y-1">
              <li>• 实时内容同步</li>
              <li>• 增加视频教程支持</li>
              <li>• 优化搜索算法</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
} 